### ISSUE TITLE
Joplin的输入法候选字框挡字母

### ISSUE THREAD

**Issue by zhousone** [rxliuli/site#1]
我在使用Joplin的windows x64版本客户端写笔记的时候，使用win10自带微软输入法，输入中文会出现候选字框挡了近一半输入的字母，很别扭，能否帮提个问题给Joplin的开发者，解决下这个问题？

**Comment by rxliuli** [comment]
请去官方 joplin repo 提 issue，ref: <https://github.com/laurent22/joplin/issues>
